[package]
name = "markedit"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
description = "A library for manipulating unstructured Markdown documents."

[dependencies]
pulldown-cmark = "0.6.1"
